import * as fs from 'fs';
import * as path from 'path';
import * as vscode from 'vscode';

/**
 * Fixes common LLM Mermaid output issues within ```mermaid blocks:
 *  - literal `\n` inside node labels → `<br/>`
 *  - node labels containing `(` or `)` without quotes → quoted
 *    (parentheses are shape-defining chars in Mermaid and break unquoted labels)
 */
export function normalizeMermaidBlocks(markdown: string): string {
  return markdown.replace(/```mermaid\n([\s\S]*?)```/g, (_, block: string) => {
    const fixed = block.split('\n').map(fixNodeLabels).join('\n');
    return '```mermaid\n' + fixed + '```';
  });
}

function fixNodeLabels(line: string): string {
  return line.replace(/\[([^\]]+)\]/g, (_, label: string) => {
    let fixed = label.replace(/\\n/g, '<br/>');
    if (/[()]/.test(fixed) && !fixed.startsWith('"')) {
      fixed = `"${fixed}"`;
    }
    return `[${fixed}]`;
  });
}

export function getDocsFolder(): string {
  const cfg = vscode.workspace.getConfiguration('docsAgent');
  return cfg.get<string>('docsFolder', 'docs');
}

export function writeDoc(
  content: string,
  sourceFilePath: string,
  workspaceRoot: string,
  modelLabel?: string
): string {
  const docsFolder = getDocsFolder();
  const relative = path.relative(workspaceRoot, sourceFilePath);
  const outputPath = path.resolve(workspaceRoot, docsFolder, `${relative}.md`);
  if (!outputPath.startsWith(path.resolve(workspaceRoot) + path.sep)) {
    throw new Error(`Cannot write documentation outside the workspace: ${sourceFilePath}`);
  }

  const header = `<!-- AI-generated by Docs Agent (${modelLabel ?? 'unknown model'}) — EU AI Act Art. 50 disclosure -->\n\n`;

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, header + content, 'utf8');

  return outputPath;
}

export async function openDoc(outputPath: string): Promise<void> {
  const uri = vscode.Uri.file(outputPath);
  await vscode.commands.executeCommand('markdown.showPreviewToSide', uri);
}
